---
- name: Install Postgresql server
  apt: 
    name: "{{ item }}-{{ postgresql.version }}"
    state: installed
    update-cache: yes
  register: pg_install
  with_items:
    - postgresql
    - postgresql-client
    - postgresql-contrib
  tags:
    - packages

- name: Configure Postgresql server
  template:
    src: "postgresql.conf.{{ postgresql.version }}.j2"
    dest: "/etc/postgresql/{{ postgresql.version }}/main/postgresql.conf"
    owner: "{{ postgresql.user }}"
    group: "{{ postgresql.group }}"
  notify:
    - reload postgresql service
  tags:
    - configuration

